// Imageboard.Frontend/src/components/Home.vue
<template>
    <div id="home">
        <div id="content">
            <hr />

            <div class="row">
                <div class="full-width">
                    <h3 class="text-center">Boards</h3>
                    <ul id="homepage__boards-list" class="list-group">
                        <li class="list-group-item homepage__board borderless" v-for="(board, index) in boards" :key="index">
                            <strong>
                                <router-link :to="board.abbr">/{{ board.abbr }} - {{ board.name }}</router-link>
                            </strong>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
    import { Component, Prop, Vue } from 'vue-property-decorator'
    import { Constants } from '../common'
    import BoardsDescriptionControl from './controls/BoardsDescriptionControl.vue'

    @Component({
        components: {
            BoardsDescriptionControl
        }
    })
    export default class Home extends Vue {
        @Prop() private boards!: Array<{ abbr: string, name: string }>;

        get imageboard(): string {
            return Constants.ImageboardName;
        }
    }
</script>

<style scoped lang="scss">
    a {
        text-decoration: none;
        color: #337ab7;

        :hover, :focus {
            color: #23527c;
            text-decoration: underline;
        }

        :focus {
            outline: thin dotted;
            outline: 5px auto -webkit-focus-ring-color;
            outline-offset: -2px;
        }
    }

    #homepage__boards-list {
        text-align: center;
    }

    .homepage__board {
        position: relative;
        min-height: 1px;
        padding-right: 20px;
        padding-left: 20px;
        width: 15%;
        float: left;
    }
</style>

// Imageboard.Frontend/src/components/Pages/Home/Home.tsx
import React from 'react';
import { Link } from 'react-router-dom';

import BoardsDescriptionControl from '../../Controls/BoardsDescriptionControl/BoardsDescriptionControl';
import { BoardsInfo, Constants } from '../../../common';

import './Home.scss';

type Props = {
    boardsInfo: BoardsInfo[];
}

export default class Home extends React.Component<Props> {
    render() {
        return(
            <div id="content">
                <div id="description">
                    <BoardsDescriptionControl name={Constants.ImageboardName} />
                </div>

                <hr />

                <div className="row">
                    <div className="full-width">
                        <h3 className="text-center">Boards</h3>
                        <ul id="homepage__boards-list" className="list-group">
                            {this.props.boardsInfo.map((item, key) => {
                                return (
                                    <li className="list-group-item homepage__board borderless" key={key}>
                                        <strong>
                                            <Link to={item.abbr} className="homepage__board__link">{item.abbr} — {item.name}</Link>
                                        </strong>
                                    </li>
                                );
                            })}
                        </ul>
                    </div>
                </div>
            </div>
        );
    }
}
