// Imageboard.Frontend/src/components/Home.vue
<template>
    <div id="home">
        <div id="content">
            <hr />

            <div class="row">
                <div class="full-width">
                    <h3 class="text-center">Boards</h3>
                    <ul id="homepage__boards-list" class="list-group">
                        <li class="list-group-item homepage__board borderless" v-for="(board, index) in boards" :key="index">
                            <strong>
                                <router-link :to="board.abbr">/{{ board.abbr }} - {{ board.name }}</router-link>
                            </strong>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
    import { Component, Prop, Vue } from 'vue-property-decorator'
    import { Constants } from '../common'
    import BoardsDescriptionControl from './controls/BoardsDescriptionControl.vue'

    @Component({
        components: {
            BoardsDescriptionControl
        }
    })
    export default class Home extends Vue {
        @Prop() private boards!: Array<{ abbr: string, name: string }>;

        get imageboard(): string {
            return Constants.ImageboardName;
        }
    }
</script>

<style scoped lang="scss">
    a {
        text-decoration: none;
        color: #337ab7;

        :hover, :focus {
            color: #23527c;
            text-decoration: underline;
        }

        :focus {
            outline: thin dotted;
            outline: 5px auto -webkit-focus-ring-color;
            outline-offset: -2px;
        }
    }

    #homepage__boards-list {
        text-align: center;
    }

    .homepage__board {
        position: relative;
        min-height: 1px;
        padding-right: 20px;
        padding-left: 20px;
        width: 15%;
        float: left;
    }
</style>

// Frontend/src/pages/home/index.tsx
import React from 'react';
import { Link } from 'react-router-dom';

import { BoardsDescription } from '../../components'
import { Board, Constants } from '../../utils/common';

import './styles.scss';

type Props = {
    links: Board[];
}

export const HomePage: React.FC<Props> = ({ links }) => (
    <>
        <BoardsDescription name={Constants.ImageboardName} abbr="/" />

        <hr />

        <div className="row">
            <div className="full-width">
                <h3 className="text-center">Boards</h3>
                <ul id="homepage__boards-list" className="list-group">
                    {links.map((item, key) => {
                        return (
                            <li className="list-group-item homepage__board borderless" key={key}>
                                <strong>
                                    <Link to={item.Abbr} className="homepage__board__link">{item.Abbr} — {item.Name}</Link>
                                </strong>
                            </li>
                        );
                    })}
                </ul>
            </div>
        </div>
    </>
);
